from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from endpoints import api_router


app = FastAPI()
app.include_router(api_router, prefix="/api")


# Mount the dist folder generated by the frontend (react)
DIST_DIR = Path(__file__).resolve().parents[2] / "frontend" / "dist"
app.mount("/assets", StaticFiles(directory=DIST_DIR / "assets"), name="assets")


@app.get("/{full_path:path}")
async def spa_fallback(full_path: str):
    """
    Serve the SPA for any non-API path.

    A real file in dist/ (favicon, manifest, robots.txt, ...) is returned
    as-is. Anything else returns index.html so that deep links and page
    refreshes on nested client routes (e.g. /dashboard/settings) load the app
    and let React Router resolve the route in the browser.
    """

    # Keep unknown /api/* paths as JSON 404s instead of silently handing back
    # index.html.
    if full_path == "api" or full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="Not found")

    candidate = DIST_DIR / full_path
    if full_path and candidate.is_file():
        return FileResponse(candidate)

    return FileResponse(DIST_DIR / "index.html")
